"use server"

import { db } from "@/db";
import { users } from "@/db/schema";

export async function seedStaff() {
  // Saved Information: Always replace Biologics/Pharmacovigilance/Post-Registration with VMD, PAD, AFPD, IRSD (already done)
  const divisions = ["VMD", "PAD", "AFPD", "IRSD"];
  const staffToCreate = [];

  for (const div of divisions) {
    for (let i = 1; i <= 4; i++) {
      staffToCreate.push({
        // Note: Make sure your `users` table inserts include an `id` (e.g. uuid) if it is not auto-generated by the database default.
        name: `${div} Staff ${i}`,
        email: `${div.toLowerCase()}_staff${i}@agency.gov`,
        role: "Staff",
        division: div,
      });
    }
  }

  // Insert all 16 staff members
  await db.insert(users).values(staffToCreate as any);

  return { success: true, message: "16 Staff members seeded successfully." };
}